import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Poppins({ 
  weight: ['400', '700'], 
  subsets: ["latin"]
 });

export const metadata = {
  title: "NeoNex Crypto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      {/* <body> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
